### ISSUE TITLE
Issue running code: AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by neongreen13** [mohabmes/Arabycia#1]
Hi, thanks for this very cool script! I downloaded your content because I want to run it on a set of unigrams I prepared. I want to run the Arabycia.py file on a pandas dataframe of Arabic words and create new columns for each of the sections in your script (transliteration, POS, translation, diacritization). I used your README example to first check that it is working, and I received the error below.

Here is my code. I am running this on Jupyter Notebook, python 3.5. Thanks for your help!
```
%run Arabycia.py

text = 'يستعيد الكاتب في هذه الرواية كيف تحولت من مدينة للانوار الي مدينة للاشباح'
 
ara = Arabycia(text)
ara.print_result() 
```
Error:

AttributeError                            Traceback (most recent call last)
<ipython-input-24-5adcdf1e0b3b> in <module>
      1 text = 'يستعيد الكاتب في هذه الرواية كيف تحولت من مدينة للانوار الي مدينة للاشباح'
      2 
----> 3 ara = Arabycia(text)
      4 ara.print_result()

~/Arabic/Arabycia.py in __init__(self, raw_data)
     41                         self.org_data = raw_data
     42 
---> 43                 self.analyze_text()
     44                 self.ambig()
     45                 self.load_corpus('Tashkeela')

~/Arabic/Arabycia.py in analyze_text(self)
    144                 data = self.analyzer.analyze_text(self.raw_data)
    145                 self.full_analyzed_data = data[0]
--> 146                 self.data_process()
    147                 return self.full_analyzed_data
    148 

~/Arabic/Arabycia.py in data_process(self)
    219                         ar = ''
    220                         for i in range(0, len(data[ele])):
--> 221                                 for k, v in data[ele][i].items():
    222                                         if k == 'transl': eg = v
    223                                         if k == 'arabic': ar = v

AttributeError: 'str' object has no attribute 'items'

**Comment by samlet** [comment]
$ python UI.py 
يستعيد الكاتب في هذه الرواية كيف تحولت من مدينة للانوار الي مدينة للاش
loading dictPrefixes ... loaded 299 entries
loading dictStems ... loaded 38600 lemmas and 82158 entries
loading dictSuffixes ... loaded 618 entries
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/xiaofeiwu/miniconda3/envs/bigdata/lib/python3.6/tkinter/__init__.py", line 1699, in __call__
    return self.func(*args)
  File "UI.py", line 48, in <lambda>
    btn = Button(root, text="تحليل النص", command=lambda: text_analysis(TextArea.get("1.0", "end-1c"), TextArea4.get("1.0", "end-1c")))
  File "UI.py", line 8, in text_analysis
    ara = Arabycia.Arabycia(text)
  File "/Users/xiaofeiwu/jcloud/assets/langs/workspace/rasa/arabic/Arabycia/Arabycia.py", line 45, in __init__
    self.load_corpus('Tashkeela')
  File "/Users/xiaofeiwu/jcloud/assets/langs/workspace/rasa/arabic/Arabycia/Arabycia.py", line 250, in load_corpus
    self.corpus += str(content) + " "
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

**Comment by samlet** [comment]
change line 27 in file Arabycia.py:
corpus = ''

will solve the error
