### ISSUE TITLE
ModuleNotFoundError: No module named 'SinaiCorpus'

### ISSUE THREAD

**Issue by mohammed-hakim** [mohabmes/Arabycia#3]
hi sear i really apreciate your work to improve nlp for the arabic language 
i just wanna ask about this error i tried to install it but not found

**Comment by mohammed-hakim** [comment]
closed
i just cloned your other package 
thnx

**Comment by ygorg** [comment]
The link is https://github.com/mohabmes/Sinai-corpus FYI.
You should clone "Sinai-corpus" in "Arabycia" directory and rename it to "SinaiCorpus".

```bash
cd Arabycia
git clone https://github.com/mohabmes/Sinai-corpus SinaiCorpus
```
